### PR TITLE
Update to v2.0.0-rc6

### PR DESCRIPTION
**Pull request by stiiifff**

### CODE REVIEW

**Comment by stiiifff** [comment]
When the following PR have been merged to the respective repo, update relevant deps (remove branch & use master/v2.0.0-rc6 tags instead):

- Product registry: https://github.com/stiiifff/pallet-product-registry/pull/19
- Product tracking: https://github.com/stiiifff/pallet-product-tracking/pull/35
- Substrate RBAC: https://github.com/gautamdhameja/substrate-rbac/pull/6
- Substrate Validator Set: https://github.com/gautamdhameja/substrate-validator-set/pull/2

**Comment by jimmychu0807** [comment]
I want to give this a good to go. After compiling everything and run the frontend, I get the following screen.

Screenshot 2020-09-17 at 21 04 37

It is dinner time. Let me get back on this after dinner. Or will be great if anyone could help solve this issue.

And @stiiifff, thanks for upgrading the numerous packages to v2.0.0-rc6!

**Comment by stiiifff** [comment]
Thx @jimmychu0807. I didn't get the issue you mentioned in the UI.

**Review by danforbes — APPROVED** [review]

**Comment by jimmychu0807** [comment]
The 2nd time I compile, it looks good now. Sorry for the false alarm

**Review by jimmychu0807 — APPROVED** [review]

**Comment by stiiifff** [comment]
@jimmychu0807 @danforbes Awesome thx guys.
But I still have issues with the Polkadot.js Apps, can't do a simple transfer.

**Comment by stiiifff** [comment]
The issue I am witnessing seems awfully similar to this one: https://github.com/polkadot-js/apps/issues/3504

**Comment by danforbes** [comment]
You need to add the types in this file https://github.com/substrate-developer-hub/substrate-enterprise-sample/blob/master/ui/src/config/common.json#L4 to the Settings > Developer tab of Apps UI https://polkadot.js.org/apps/#/settings/developer.

**Comment by danforbes** [comment]
@jimmychu0807 someone else had actually reported this exact same issue to me so good to be aware of :+1: 
> the 2nd time I compile (with node_modules removed), it looks good now. Sorry for the false alarm

**Comment by stiiifff** [comment]
@danforbes I had actually done that. I'll give another try.
LGTM

**Pull request merged**
