### PR TITLE
Vendor pallets & update docs

### PR DESCRIPTION
**Pull request by danforbes**

### CODE REVIEW

**Comment by gautamdhameja** [comment]
Why are we copying permissioning pallets' source code in here?

**Comment by jimmychu0807** [comment]
I think we had a discussion that it becomes difficult to maintain and update the enterprise-sample. There are 4-5 separate pallets we need to update here and there. By aggregating them altogether, we can just update everything within this repo. 

This is the nice part I see about the update. 

I understand some pallets, like `pallet-rbac` is generic enough to be reused in other projects. So the question is if we want to separate these pallets out (so there is still a generic version of `pallet-rbac` and the one in this repo is enterprise-sample specific) and ease the ongoing maintenance of enterprise sample?

**Comment by riusricardo** [comment]
@jimmychu0807  I agree that it is difficult to update many repos. The best approach is to copy pallets that have specific logic  (#57 ) and keep the generic ones on their own repos. As I said to @danforbes we could fork the repos and have a copy of Gautam's pallets in the DevHub org. Then it will be easier to keep track of any upstream improvements and could be that some changes may go upstream.

**Comment by danforbes** [comment]
Replaced by #60

**Pull request closed without merging**
